# Generated by Django 6.0.6 on 2026-06-13 12:39

import django.db.models.deletion
from django.db import migrations, models


def move_author_names_to_author_rows(apps, schema_editor):
    Post = apps.get_model('blog', 'Post')
    Author = apps.get_model('blog', 'Author')

    for post in Post.objects.all():
        author_name = str(post.author).strip() or 'Unknown Author'
        author, _ = Author.objects.get_or_create(
            name=author_name,
            defaults={'email': f'{author_name.lower().replace(" ", ".")}@example.com'},
        )
        post.author = str(author.id)
        post.save(update_fields=['author'])


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_author_tag_comment_postdetail_post_tags'),
    ]

    operations = [
        migrations.RunPython(move_author_names_to_author_rows, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.author'),
        ),
    ]
